version: '3'
services:
  sample_terraform:
    container_name: sample_terraform
    image: hashicorp/terraform:0.14.7
    env_file:
      - .env
    volumes:
      - .:/terraform
    working_dir: /terraform
    entrypoint: ash
    tty: true