version: '3'
services:
  sample_terraform:
    container_name: sample_terraform
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/terraform
    working_dir: /terraform
    entrypoint: ash
    tty: true